import { mode } from "@chakra-ui/theme-tools";

export const ButtonStyles = {
  baseStyle: {
    fontSize: "sm",
  },
  sizes: {},
  variants: {
    button1: (props: any) => ({
      bg: "#EA4C89",
      py: "6",
      borderRadius: "8px",
      border: "none",
      boxSizing: "border-box",
      color: "#FFFFFF",
      cursor: "pointer",
      display: "inline-block",
      fontFamily: "inherit",
      fontSize: "14px",
      fontWeight: "500",
      height: "40px",
      lineHeight: "20px",
      listStyle: "none",
      margin: 0,
      outline: "none",
      padding: "10px 16px",
      position: "relative",
      textAlign: "center",
      textDecoration: "none",
      transition: "color 100ms",
      verticalAlign: "baseline",
      userSelect: "none",
      WebkitUserSelect: "none",
      touchAction: "manipulation",
      _hover: {
        bg: mode("#F082AC", "#da9109")(props),
      },
      _focus: {
        bg: "#F082AC",
      },
    }),
    button2: (props: any) => ({
      fontSize: "14px",
      fontWeight: "500",
      lineHeight: "20px",
      display: "inline-block",
      textAlign: "center",
      borderRadius: "8px",
      borderWidth: "0",
      padding: "10px 12px",
      cursor: "pointer",
      color: "#333333",
      backgroundColor: "rgba(51, 51, 51, 0.05)",
      transition: "all 200ms",
      listStyle: "none",
      margin: 0,
      whiteSpace: "nowrap",
      userSelect: "none",
      WebkitUserSelect: "none",
      touchAction: "manipulation",
      _hover: {
        bg: mode("rgba(51, 51, 51, 0.1)", "rgba(255, 255, 255, 0.05)"),
      },
    }),
    button3: (props: any) => ({
      fontSize: "14px",
      fontWeight: "600",
      lineHeight: "20px",
      display: "inline-block",
      textAlign: "center",
      borderRadius: "6px",
      borderWidth: "1px",
      borderColor: "rgba(27, 31, 35, .15)",
      boxShadow: "rgba(27, 31, 35, .1) 0 1px 0",
      padding: "6px 16px",
      cursor: "pointer",
      color: "#fff",
      backgroundColor: "#2ea44f",
      transition: "background-color 200ms, box-shadow 200ms",
      textDecoration: "none",
      userSelect: "none",
      WebkitUserSelect: "none",
      touchAction: "manipulation",
      whiteSpace: "nowrap",
      _hover: {
        bg: mode("#2c974b", "#2ea44f"),
      },
      _focus: {
        boxShadow: `rgba(46, 164, 79, .4) 0 0 0 3px`,
        outline: "none",
      },
      _disabled: {
        bg: "#94d3a2",
        borderColor: "rgba(27, 31, 35, .1)",
        color: "rgba(255, 255, 255, .8)",
        cursor: "default",
      },
      _active: {
        bg: "#298e46",
        boxShadow: "rgba(20, 70, 32, .2) 0 1px 0 inset",
      },
    }),
    button86: (props: any) => ({
      all: "unset",
      width: "100px",
      height: "30px",
      fontSize: "16px",
      bg: "transparent",
      border: "none",
      position: "relative",
      color: "#f0f0f0",
      cursor: "pointer",
      zIndex: 1,
      padding: "10px 20px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      whiteSpace: "nowrap",
      userSelect: "none",
      WebkitUserSelect: "none",
      touchAction: "manipulation",
      _after: {
        content: '""',
        position: "absolute",
        bottom: 0,
        right: 0,
        zIndex: -99999,
        transition: "all .4s",
        transform: "translate(0%, 0%)",
        width: "100%",
        height: "100%",
        bg: mode("#28282d", "#ffffff")(props),
        borderRadius: "10px",
      },
      _before: {
        content: '""',
        position: "absolute",
        bottom: 0,
        right: 0,
        zIndex: -99999,
        transition: "all .4s",
        transform: "translate(10px, 10px)",
        width: "35px",
        height: "35px",
        bg: mode("#ffffff15", "#ffffff15")(props),
        backdropFilter: "blur(5px)",
        WebkitBackdropFilter: "blur(5px)",
        borderRadius: "50px",
      },
      _hover: {
        _before: {
          transform: "translate(5%, 20%)",
          width: "110%",
          height: "110%",
        },
        _after: {
          borderRadius: "10px",
          transform: "translate(0, 0)",
          width: "100%",
          height: "100%",
        },
      },
      _active: {
        _after: {
          transition: "0s",
          transform: "translate(0, 5%)",
        },
      },
    }),
    primaryOutline: (props: any) => ({
      bg: "transparent",
      border: "1px solid",
      color: mode("primary", "white")(props),
      _hover: {
        transform: "scale(1.02)",
        border: "1px solid",
        boxShadow: "md",
      },
    }),
    secondary: (props: any) => ({
      bg: "secondary",
      color: "white",
      _hover: {
        bg: mode("#1944ab", "#0b2050")(props),
        boxShadow: "md",
      },
    }),
    tertiary: () => ({
      bg: "transparent",
      border: "1px solid #FFFFFF",
      color: "#FFFFFF",
      textTransform: "uppercase",
      _hover: {
        transform: "scale(1.02)",
        padding: "3px",
        border: "1px solid",
        boxShadow: "md",
      },
    }),
    special1: (props: any) => ({
      bg: "transparent",
      border: "2px solid gainsboro",
      color: mode("black", "white")(props),
      _hover: {
        transform: "scale(1.02)",
        border: "2px solid",
        boxShadow: "md",
      },
    }),
  },
  defaultProps: {},
};
